image: docker

stages:
  - build

build_commit:
  stage: build
  except:
    - tags
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^(feat|fix|perf|test)*/i
  services:
  - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA . 
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build_commit_tag:
  stage: build
  only:
    - tags
  services:
  - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG . 
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
